class DataPaths:
    CITY_TARGET_PASSENGER_RATING = 'csv_files/city_target_passenger_rating.csv'
    DIM_CITY = 'csv_files/dim_city.csv'
    DIM_DATE = 'csv_files/dim_date.csv'
    DIM_REPEAT_TRIP_DISTRIBUTION = 'csv_files/dim_repeat_trip_distribution.csv'
    FACT_PASSENGER_SUMMARY = 'csv_files/fact_passenger_summary.csv'
    FACT_TRIPS = 'csv_files/fact_trips.csv'
    MONTHLY_TARGET_NEW_PASSENGERS = 'csv_files/monthly_target_new_passengers.csv'
    MONTHLY_TARGET_TRIPS = 'csv_files/monthly_target_trips.csv'
    BACKGROUND_IMAGE = 'video_presentation_background_img.jpg'
